---
broadcast_topic: lorax.ldtboresight.camera1.broadcast
broker_hosts:
  - tanagra
  - 61613
camera_host: 127.0.0.1
camera_port: 7624
camera_type: QHY600
dto_topic: lorax.ldtboresight.camera1.dto
incoming_topic: lorax.ldtboresight.dto.camera1
log_file: qhy_camera.log