---
log_file: dto.log
broker_hosts:
  - tanagra
  - 61613
mount_command_topic: lorax.timo.dto.mount
mount_incoming_topic: lorax.timo.mount.broadcast
camera_command_topic: lorax.timo.dto.camera
camera_incoming_topic: lorax.timo.camera.broadcast
mount_type: PWI4
camera_type: SBIG ST-10X
command_input_file: command_test
